name: Docker Publish

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: ['main']

permissions:
  contents: read

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@master
        with:
          name: jar-file
          path: app.jar
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: douglasjohnson/spring-boot-open-api-mongodb:latest
